apiVersion: v1
kind: Service
metadata:
  name:  project-rtp-service
  namespace: project-ns
spec:
  type: NodePort
  selector:
    app: project-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
